### ISSUE TITLE
Error with KOReaderJsonALLtoEachBook.py

### ISSUE THREAD

**Issue by zenminimalist** [wangandi520/ClippingsToMarkdown#3]
I'm currently running the latest KOReader. And as I tried to convert my JSON clipping and get the following error. 

`ClippingsToMarkdown % python3 KOReaderJsonALLtoEachBook.py /Users/XXX/Dropbox/Apps/Kindle/ClippingsToMarkdown/KOReaderClipping.json
Traceback (most recent call last):
  File "/Users/XXXX/Dropbox/Apps/Kindle/ClippingsToMarkdown/KOReaderJsonALLtoEachBook.py", line 63, in <module>
    main(sys.argv)
  File "/Users/XXX/Dropbox/Apps/Kindle/ClippingsToMarkdown/KOReaderJsonALLtoEachBook.py", line 58, in main
    converterFromKOReaderJson(aPath)
  File "/Users/XXXX/Dropbox/Apps/Kindle/ClippingsToMarkdown/KOReaderJsonALLtoEachBook.py", line 38, in converterFromKOReaderJson
    jsonData = json.loads(eachBook)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`

Not sure what the issue is. If it's some type of dependency or with the ClippingsToMarkdown code. [Here's](https://pastebin.com/02qMs0Mq) the clipping file that I have.

Also, is there a way to add [this](https://github.com/wangandi520/ClippingsToMarkdown/issues/1#issuecomment-1060739156) to the code as well? I don't see this part in the code as it was the case in the Onyx version where you could change the way the author, title etc. is formatted in the MD file.

**Comment by wangandi520** [comment]
hi,sorry for late reply,email failed to connect.

I checked 2022.11 koreader,maybe koreader's clipping format is update,I will find sometime to update the script.I can not find menu to export clipping and found in xxx.epub.lua.Where to find export

my old clipping worked fine. https://pastebin.com/qqW6m2g5

**Comment by wangandi520** [comment]
hi,sorry for late reply,email failed to connect.

I checked 2022.11 koreader,maybe koreader's clipping format is update,I will find sometime to update the script.I can not find menu to export clipping and found in xxx.epub.lua.Where to find export

my old clipping is worded fine. https://pastebin.com/qqW6m2g5
